# Generated by Django 5.1 on 2024-09-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_code', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_code', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_code', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GRRegister',
            fields=[
                ('gr_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_admission', models.DateField()),
                ('last_school', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_number_1', models.CharField(max_length=15)),
                ('cell_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_removal', models.DateField(blank=True, null=True)),
                ('present', models.BooleanField(default=True)),
                ('class_of_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes')),
                ('class_of_removal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_students', to='student.classes')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes')),
                ('gr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.grregister')),
                ('section_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.section')),
                ('session_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.session')),
            ],
        ),
    ]
