# Generated by Django 5.1 on 2024-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grregister',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
