# Generated by Django 5.1.1 on 2024-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_grregister_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grregister',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
