# Generated by Django 5.1.1 on 2024-10-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_alter_concession_concession_remarks_and_more'),
        ('student', '0003_alter_grregister_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='grregister',
            name='concession_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fee.concession'),
            preserve_default=False,
        ),
    ]
