# Generated by Django 5.1.1 on 2024-10-16 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_alter_fee_class_code'),
        ('student', '0004_grregister_concession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grregister',
            name='concession_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.concession'),
        ),
    ]
