# Generated by Django 5.1.1 on 2024-10-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_alter_grregister_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('concession_code', models.AutoField(primary_key=True, serialize=False)),
                ('concession_type', models.CharField(max_length=100)),
                ('concession_amount', models.IntegerField(default=0)),
                ('concession_persent', models.IntegerField(default=0)),
                ('concession_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('fee_code', models.AutoField(primary_key=True, serialize=False)),
                ('fee_type', models.CharField(max_length=100)),
                ('fee_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.IntegerField()),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_amount', models.IntegerField()),
                ('submit_amount', models.IntegerField()),
                ('mounth', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('fee_status', models.BooleanField()),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes')),
                ('gr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.grregister')),
                ('section_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.section')),
            ],
        ),
    ]
