# Generated by Django 5.1.1 on 2024-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='concession_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='fee_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
