# Generated by Django 5.1.1 on 2024-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_alter_concession_concession_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='submit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
