# Generated by Django 5.1.1 on 2024-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_alter_fee_submit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='submit_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
