# Generated by Django 5.1.1 on 2024-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_alter_fee_due_amount_alter_fee_submit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='concession_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='concession',
            name='concession_persent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
