# Generated by Django 5.1.1 on 2024-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0005_alter_concession_concession_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='concession_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='concession',
            name='concession_persent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
