# Generated by Django 5.1.1 on 2024-10-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0007_alter_fee_class_code'),
        ('student', '0004_grregister_concession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes'),
        ),
    ]
