# Generated by Django 5.1.1 on 2024-10-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_alter_fee_class_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='mounth',
        ),
    ]
