# Generated by Django 5.1.1 on 2024-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0010_remove_fee_mounth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='class_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fee',
            name='gr_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fee',
            name='section_code',
            field=models.CharField(max_length=200),
        ),
    ]
